name: Common1
on:
  workflow_call:
    inputs:
      test_data:
        required: true
        type: string
        default: "test data"
      test_data1:
        required: false
        type: string
        default: "test data1"
      event_inputs:
        required: false
        type: string
        
    secrets:
      FIRST_SECRET:
        required: true
        
env:
  ENV_TEST1: ${{ fromJson(inputs.event_inputs)['test1'] }}
  ENV_TEST2: ${{ secrets.TEST2 }}
        
        
jobs:
  common_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: print env
        env:
          ENV_VAR_NAME: ${{ secrets.FIRST_SECRET }}
        run: echo $ENV_VAR_NAME >> secrets.txt
      - name: print input
        run: echo ${{inputs.test_data}}
      
