name: Common1
on:
  workflow_call:
    inputs:
      test_data:
        required: true
        type: string
        default: "test data"
        
        
jobs:
  common_build:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        env:
          ENV_VAR_NAME: ${{ secrets.FIRST_SECRET }}
        run: echo $ENV_VAR_NAME
      - name: print input
        run: echo ${{inputs.test_data}}
      
