name: Common1
on:
  workflow_call:
    inputs:
      test_data:
        required: true
        type: string
        default: "test data"
    secrets:
      FIRST_SECRET:
        required: true
        
        
jobs:
  common_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: print env
        env:
          ENV_VAR_NAME: ${{ secrets.FIRST_SECRET }}
        run: echo $ENV_VAR_NAME >> secrets.txt
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
      - name: print input
        run: echo ${{inputs.test_data}}
      
